#ifndef GOBLIB_M5S_VERSION_HPP
#define GOBLIB_M5S_VERSION_HPP

#define GOBLIB_M5S_VERSION_MAJOR 0
#define GOBLIB_M5S_VERSION_MINOR 2
#define GOBLIB_M5S_VERSION_PATCH 0

#define GOBLIB_M5S_VERSION_STRINGIFY_AGAIN(x) #x
#define GOBLIB_M5S_VERSION_STRINGIFY(x) GOBLIB_M5S_VERSION_STRINGIFY_AGAIN(x)

#define GOBLIB_M5S_VERSION_VALUE ((GOBLIB_M5S_VERSION_MAJOR << 16) | (GOBLIB_M5S_VERSION_MINOR << 8) | (GOBLIB_M5S_VERSION_PATCH))
#define GOBLIB_M5S_VERSION_STRING GOBLIB_M5S_VERSION_STRINGIFY(GOBLIB_M5S_VERSION_MAJOR.GOBLIB_M5S_VERSION_MINOR.GOBLIB_M5S_VERSION_PATCH)

#endif
